sudo: required

services:
  - docker

before_script:
  - docker info

script:
  - docker build -t athena .
  - docker run --rm athena make test GCOV=1
  - docker run --rm athena make valgrind-test DEBUG=1
  - docker run --rm athena make test HAVE_CBLAS=1
  - docker run --rm athena make main
